### ISSUE TITLE
error about  PluginlibFactory: The plugin for class 'VoronoiGraph' failed to load.

### ISSUE THREAD

**Issue by lxa199709** [tanujthakkar/Voronoi-Based-Hybrid-Astar#1]
excuse me ,could you give some advice on solving the error about "PluginlibFactory: The plugin for class 'VoronoiGraph' failed to load.",i have no idea about how to solve this.highly appreciate  for  your help!

**Comment by Joyuan-sys** [comment]
> excuse me ,could you give some advice on solving the error about "PluginlibFactory: The plugin for class 'VoronoiGraph' failed to load.",i have no idea about how to solve this.highly appreciate for your help!

Ihave met the same problem, how to solve it?

**Comment by tanujthakkar** [comment]
> > excuse me ,could you give some advice on solving the error about "PluginlibFactory: The plugin for class 'VoronoiGraph' failed to load.",i have no idea about how to solve this.highly appreciate for your help!
> 
> Ihave met the same problem, how to solve it?

Hi, could you confirm if this is an issue on the jsk package side of things? Please provide the entire error message. Also, try the following and rebuilding the package.

```sudo apt-get install ros-ROS_DISTRO-jsk-rviz-plugins```

**Comment by Joyuan-sys** [comment]
Thank you for your answer, but my problem is still not solved, how did you generate your Voronoi diagram?
![image](https://user-images.githubusercontent.com/72717363/185969617-0c748b7c-818f-47ea-bf34-3130c42035e6.png)

**Comment by tanujthakkar** [comment]
> Thank you for your answer, but my problem is still not solved, how did you generate your Voronoi diagram? ![image](https://user-images.githubusercontent.com/72717363/185969617-0c748b7c-818f-47ea-bf34-3130c42035e6.png)

The voronoi graph should be generated automatically when you run the launch file. The repo uses [tuw_multi_robot](https://github.com/tuw-robotics/tuw_multi_robot) to generate a voronoi graph and then performs some post-processing to be used with the planning algorithm. Please follow the installation instructions as provided. Also, try deleting the contents of cache in maps/voronoi/cache.

**Comment by yanyifengbupt** [comment]
> excuse me ,could you give some advice on solving the error about "PluginlibFactory: The plugin for class 'VoronoiGraph' failed to load.",i have no idea about how to solve this.highly appreciate for your help!

针对这个问题，可以将这个链接  [https://github.com/tuw-robotics/tuw_multi_robot/tree/melodic/tuw_multi_robot_rviz](url)  里的 tuw_multi_robot_rviz文件夹复制到你的代码里来解决
