### ISSUE TITLE
[graph_generator-3] process has died

### ISSUE THREAD

**Issue by zhthree3** [tanujthakkar/Voronoi-Based-Hybrid-Astar#2]
when I roslaunch hybrid_astar hybrid_astar.launch, the following error will occur:

[ INFO] [1694166247.667911578]: Initialization done!
[ INFO] [1694166247.894985004]: Recieved the occupancy grid map
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  input stream error-Resource temporarily unavailable
[graph_generator-3] process has died [pid 1382514, exit code -6, cmd /home/zh/Hybrid_AStar/voronoi_hybrid_astar_ws/devel/lib/tuw_voronoi_graph/tuw_voronoi_graph_node __name:=graph_generator __log:=/home/zh/.ros/log/01b74278-4e2b-11ee-bcb6-8d787f079bca/graph_generator-3.log].
log file: /home/zh/.ros/log/01b74278-4e2b-11ee-bcb6-8d787f079bca/graph_generator-3*.log
^C[hybrid_astar-2] killing on exit
[rviz-4] killing on exit
[map_server-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by hoppss** [comment]
20.04  ros1 noetic, I also meet this error, any one solve this problem ?

**Comment by Hitoribc** [comment]
> 20.04 ros1 noetic, I also meet this error, any one solve this problem ?

me too

**Comment by tanujthakkar** [comment]
Hi @hoppss @Hitoribc, can you guys try deleting the saved Voronoi graph once? Also, before passing a start/goal in Rviz, wait for the Voronoi graph to be calculated.

**Comment by hoppss** [comment]
> Hi @hoppss @Hitoribc, can you guys try deleting the saved Voronoi graph once? Also, before passing a start/goal in Rviz, wait for the Voronoi graph to be calculated.

It solved when i deleted files below maps/cache/* . 
Thanks.

**Comment by tanujthakkar** [comment]
Yeah, seems like a bug in the Voronoi package. Might be able to solve it by including a deletion on startup in my code.
