### ISSUE TITLE
GAZEBO Model

### ISSUE THREAD

**Issue by Geonhee-LEE** [tanujthakkar/Voronoi-Based-Hybrid-Astar#3]
Hi, 
I want to have tractor-trailer the gazebo model. Would you share this code?

![image](https://github.com/tanujthakkar/Voronoi-Based-Hybrid-Astar/assets/12562147/c7799e04-486f-40e9-a2c0-5760c68749b3)
![image](https://github.com/tanujthakkar/Voronoi-Based-Hybrid-Astar/assets/12562147/b8eb197e-a9f5-4e3a-a432-631817d7bda6)

**Comment by tanujthakkar** [comment]
Anyone looking for the gazebo model - https://drive.google.com/file/d/1cIZ1vYyxNJra17fDdWht4fDzDkmV_4eT/view?usp=share_link
